name: WorkflowIaC

on:
  push:
    branches:
     - 'main'
    paths:
            #- 'frontend/**'
      - 'IaC/**.tf'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy

jobs:
  build:
    name: "Terraform_apply"
    if: ${{ github.event.inputs.action != 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    #    if: github.event.ref == 'refs/heads/main' && github.event_path == 'IaC/**'

    steps:
      - name: Print Build
        run: echo "mudou o IaC"

  terraform:
    runs-on: ubuntu-latest
    # if: github.event.ref == 'refs/heads/main' && github.event_path == 'frontend/**'
    if: ${{ github.event.path == 'IaC/**.tf' }}

    steps:
      - name: Print Terraform
        run: echo "if do IaC"

  manual:
    name: "Terraform_destroy"
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    #    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Print Manual
        run: echo "destruiu o IaC"
